export enum OrderStatus {
    SHIPPED = 'SHIPPED',
    DELIVERED = 'DELIVERED',
    INVOICED = 'INVOICED',
    CANCELED = 'CANCELED',
    OPEN = 'OPEN',
    IN_PREPARATION = 'IN_PREPARATION',
    PENDING_PAYMENT = 'PENDING_PAYMENT',
    RETURNED = 'RETURNED'
}
